### ISSUE TITLE
Incorrect cluster_name parsing with cluster names consisting of '-'

### ISSUE THREAD

**Issue by SachinBadgujar** [SumoLogic/sumologic-mongodb-atlas#8]
https://github.com/SumoLogic/sumologic-mongodb-atlas/blob/cd03218d668b5ec19aab01bc3f9cccba57eae80a/sumomongodbatlascollector/api.py#L188

The cluster_name field is derived from the hostname. 
`msg['cluster_name'] = self.hostname.split("-", 1)[0].strip()`

However, for cluster names like 'develop-amazon-canada',  the cluster_name is extracted as 'develop'. It is not consistent with the cluster name in Atlas. 

Expected: 
For Hostname=develop-amazon-canada-shard-00-01-yfrug.mongodb.net
cluster_name should be `develop-amazon-canada` 

Currently:
For Hostname=develop-amazon-canada-shard-00-01-yfrug.mongodb.net
cluster_name=`develop`

**Comment by SachinBadgujar** [comment]
@himanshu219

**Comment by himanshu219** [comment]
This will be fixed in #7

**Comment by himanshu219** [comment]
We have already released new version 1.0.15 of SAM application and 1.0.8 of onprem python package.

**Comment by SachinBadgujar** [comment]
Thank you @himanshu219 It fixed the issue.
